Chaussure/urls.py
from django.conf.urls import url
from . import views

app_name='Chaussure'
urlpatterns =[
    url(r'^$', views.all_shoes, name='all-shoes'),
    url(r'^(?P<id>\d+)$', views.shoe, name='shoe'),
    url(r'^shoeOnDemand$', views.shoe_on_demand, name='shoe_on_demand'),
    url(r'^(?P<id>\d+)/edit$', views.edit_shoe, name='edit_shoe'),
]

sitecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Chaussure.urls' , namespace='Chaussure')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chaussure/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

from django.utils import timezone 

class Chaussure(models.Model):
    nom = models.CharField(max_length=50)
    description = models.TextField(default=' ')
    img = models.ImageField(upload_to='post_img/', default="post_img/default.png")
    created_at = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default =True)
    def __str__(self):
        return self.nom

Chaussure/forms.py
from django import forms
from .models import Chaussure

class ShoeForm(forms.ModelForm):
    class Meta:
        model = Chaussure
        fields = ['nom','description','img']

Chaussure/views.py
from django.shortcuts import render , get_object_or_404 , redirect
 
# Create your views here.

from .models import Chaussure
from .forms import ShoeForm

def all_shoes(request):
    all_shoes = Chaussure.objects.filter(active=True)
    context = {
        'all_shoes' : all_shoes, 
    }
    return render(request,'all_shoes.html',context)
 

def shoe(request, id):
    #shoe =  Chaussure.objects.get(id=id)
    shoe =  get_object_or_404(Chaussure,id=id)
    context ={
        'shoe' : shoe,
    }
    return render(request,'shoeDetail.html',context)

def shoe_on_demand(request):
    if(request.method == 'POST'):
        form = ShoeForm(request.POST,request.FILES)
        form.save()
    else:
        form = ShoeForm()
    context = {
        'form' : form ,
    }

    return render(request , 'shoe_on_demand.html', context)

def edit_shoe(request, id):
    shoe = get_object_or_404(Chaussure,id=id)
    if(request.method == 'POST'):
        form = ShoeForm(request.POST,request.FILES, instance=shoe)
        form.save()
        return redirect('/')
    else:
        form = ShoeForm(instance=shoe)
    context = {
        'form' : form ,
    }
    return render(request , 'edit.html', context)
    

Chaussure/templates/all_shoes.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="split left">
    <h1>The Designer</h1>
    <a href="#" class="button">Read More</a>
  </div>
  <div class="split right">
    <h1>The Programmer</h1>
    <a href="#" class="button">Read More</a>
  </div>
</div>
    {% for shoe in all_shoes %}
    <div class="col-md-4">
    <div class="card-deck">
        <div class="card">
            {% if shoe.img %}
          <img class="card-img-top" src="{{shoe.img.url}}" alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{shoe.nom}}</h5>
            <p class="card-text">{{shoe.description | truncatewords:10}}</p>
          </div>
          <a href="{% url 'Chaussure:shoe' shoe.id %}" class="btn btn-primary">details</a>
        </div>
    </div>  
    </div>
   
   
    {% endfor %}
{% endblock body %}

Chaussure/templates/edit.html
{% extends "base.html" %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit" >save</button>
</form>
{% endblock body %}

Chaussure/templates/shoeDetail.html
{% extends "base.html" %}
{% block body %}
  
    
    <div class="card-deck shoe">
       
        <div class="card">
          <img class="card-img-top" src="{{shoe.img.url}}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{shoe.nom}}</h5>
            <p class="card-text">{{shoe.description}}</p>
          </div>
           <a href="{% url 'Chaussure:edit_shoe' shoe.id %}" class="btn btn-primary">modifier</a>
        </div>
       
      </div>
{% endblock body %}

Chaussure/templates/shoe_on_demand.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit" >Envoyer</button>
</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home-static/css/style.css' %}">
    <title>Python news</title>
</head>
<body>
   
    <div class="container"> 
        <div class="row mt-4">
          
            {% block body %}
              
            {% endblock body %}

        </div> 
    </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>